language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t szymongrabski/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true szymongrabski/react-test npm test -- --passWithNoTests

after_succes:
  - docker build -t szymongrabski/sneakerstore-frontend ./frontend
  - docker build -t szymongrabski/sneakerstore-nginx ./nginx
  - docker build -t szymongrabski/sneakerstore-backend ./backend
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push szymongrabski/sneakerstore-frontend
  - docker push szymongrabski/sneakerstore-nginx
  - docker push szymongrabski/sneakerstore-backend