services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    ports:
      - 8080:8080
    command: start-dev
    environment:
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_LOG_LEVEL=INFO
    volumes:
      - ./keycloak-auth/keycloak-data-volume:/opt/keycloak/data/
  neo4j:
    image: 'neo4j:latest'
    environment:
      NEO4J_AUTH: ${DB_USERNAME}/${DB_PASSWORD}
    ports:
      - '7474:7474'
      - '7687:7687'
  frontend:
    image: "szymongrabski/sneakerstore-frontend"
    mem_limit: 128m
    hostname: frontend
  backend:
    image: "szymongrabski/sneakerstore-backend"
    mem_limit: 128m
    hostname: backend
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_URI=$DB_URI
    env_file:
      - ./backend/src/.env
  nginx:
    image: "szymongrabski/sneakerstore-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"